### ISSUE TITLE
Supporting formatting options / more human-readable output json formatting?

### ISSUE THREAD

**Issue by mbevin** [ymglez/jsonpack#12]
I did a quick-hack for my needs - https://github.com/mbevin/jsonpack/commit/3a701adfb97d1b069d0154e4c05d13e6b90e2450 - but it's super simple and could be improved, and one could have more general flexible ability to have not only newlines, but also some degree of indentations ....

**Comment by ymglez** [comment]
``` cpp
/**
 * param pretty     if or not output will be pretty-printed
 * param indent    degree of indentation(spaces)
 * param level  for internal use
 */
char* json_pack(bool prettty, unsigned indent, unsigned level)
```
