### ISSUE TITLE
Doesn't escape strings properly

### ISSUE THREAD

**Issue by HeXetic** [ymglez/jsonpack#4]
I edited tutorial.cpp line 25 to be the following:

``` C++
src.mCad = "This, \" is a \", \'test";
```

The resulting output:

> $ ./tutorial
> json: 
> {"mFloat":3.1415927410125734,"mInt":362880,"mCad":"This, " is a ", 'test","isObject":true,"caracter":"$","cstr":"Hello, world"}
> error: error near ' ' at position 6

The JSON serializer failed to properly escape the quotation marks.

**Comment by ymglez** [comment]
You can check again about quotation marks escape. Thank's for you colaboration
