### ISSUE TITLE
Support for std::map, also enums, BetterEnums, ...?

### ISSUE THREAD

**Issue by mbevin** [ymglez/jsonpack#8]
Support for more types would be awesome. 

Regarding map/unordered_map/etc, I saw there's this umap, but it didn't seem to work when I tried using it. Perhaps an example would help there....

Also I had a quick play at trying to add support for i.e. BetterEnums' enums (i.e. enable_if<has__to_string_method> or enable_if<has__to_integral_method> depending on whether want to map them to ints or strings), but I couldn't quite work out how to add a specialization to json_traits that was based on some such enable_if templated type ...  supporting normal enums (mapping them to+from int) would be good too ....

**Comment by mbevin** [comment]
Ok, so I implemented support for any BetterEnum ( https://github.com/aantron/better-enums ) as a type (without actually adding any dependency, rather I added a template specialization for any class containing int _to_integral() (+ T::_from_integral(int) is required), which these ‘enums’ do - https://github.com/mbevin/jsonpack/commit/18e4e22e5a81f98d89c8bb6231ca9b11b0eb57b8 .

In the process I made it generally easier to add support of other types where use of enable_if is required/desired by adding a second template parameter to json_traits.

This should also help/allow you to clean-up all the different specialisations in places like integers.hpp, reducing all the different integer-type specialisations to one single enable_if<is_integral> specialisation for example, thus reducing a lot of code duplication/repetition in such places.

**Comment by mbevin** [comment]
So for example, adding support for normal enums now would just simply be a matter of doing what I did there in integers.hpp, but for std::enable_if< std::is_enum<T>>, and simply casting int to+from the enum type.

**Comment by mbevin** [comment]
Added that standard enum support to - https://github.com/mbevin/jsonpack/commit/704705a61787287781a624a85f79d14298c7b196 - tho continuing the copy-paste of the integer parsing etc - would be good to eliminate all that repeated code in that file.

**Comment by gallegogt** [comment]
Hey mbevin, I find it interesting what you're doing, once you have the implementation ready can you create you some tests and if they pass create a PR. Sincerely Yolier

**Comment by mbevin** [comment]
Cool, well yeah, its ready in a sense that it doing what I needed so far, and working and I'm using it, so if you have some tests ready let me know .... main likely issue would be that I break some (especially non-modern) compiler that you're wanting to support with some such, as given that it already doesn't build for me before my changes with VS2015, the only thing I'm testing on is xcode (clang) .... if I was to do more changes I might clean-up the code duplication in the definition of the different types (i.e. many of the duplicated methods places like in integers + serializer where you implement for all the different integral / sequential types can be reduced to one using enable_if)

**Comment by mbevin** [comment]
I made the pull-request.

**Comment by mbevin** [comment]
Ok, I pushed a fix, so now tested better, that it compiles+runs now both with make (with the examples+unit-tests) on osx, and with visual studio on windows ....

**Comment by gallegogt** [comment]
Good!!!!, tonight I'll compile the code and tell you
Best regards, Yolier

**Comment by gallegogt** [comment]
Hey mbevin, when I run

``` bash
$ cd jsonpack/build
$ ./bin/test_jsonpack_real
```

Don't pass the "real" values  test:

```
Running 2 test cases...
unknown location:0: fatal error: in "pack_unpack_reals_maximum_finite_value": jsonpack::type_error: Double out of range
/Users/ygalan/workspace/c++/mbevi_jsonpack/test/test_jsonpack_real.cpp:34: last checkpoint: "pack_unpack_reals_maximum_finite_value" entry.
unknown location:0: fatal error: in "pack_unpack_reals_min_finite_value": jsonpack::type_error: Float out of range
/Users/ygalan/workspace/c++/mbevi_jsonpack/test/test_jsonpack_real.cpp:51: last checkpoint: "pack_unpack_reals_min_finite_value" entry.
```

**Comment by mbevin** [comment]
Ah, sorry, fixed that .... looks like all your tests are properly passing now.
